;;---------------------------------------------
;; compute_frame
;;
;; Raycasting is done there, in three steps
;;---------------------------------------------
compute_frame   
                ldx #39; screen_width - 1
                stx ray_id
@loop                   lda theta
                        sec
                        sbc half_fov
                        adc ray_id
                        sta rayTheta

                        jsr init_ray_params
                        jsr cast_ray
                dec ray_id 
                bpl @loop
                rts

;;---------------------------------------------
;; draw_back_buffer
;;
;; Renders frame on a back buffer
;; Only upper half of the screen is calculated
;; Lower part is just a mirror.
;; Uses:
;; - F_16 - pointer to "upper-part" of the color_buffer
;; - G_16 - pointer to "lower-part" of the color_buffer
;; - ray_start
;; - ray_color
;;---------------------------------------------
draw_back_buffer     
                
                ldx #12
@rows                   ; update lower half pointer
                        lda backBuffLowerL,x
                        sta G_16_L
                        lda backBuffLowerH,x
                        sta G_16_H

                        ; update upper part pointer
                        lda backBuffUpperL,x
                        sta F_16_L
                        lda backBuffUpperH,x
                        sta F_16_H

                        ldy #39 ; screen_width - 1
@cols                           clc
                                txa
                                cmp ray_start,y
                                bcs @draw_walls
@draw_ceil_and_floor            lda ceil_color
                                sta (F_16),y
                                lda floor_color
                                sta (G_16),y
                                jmp @end
@draw_walls                     lda ray_color,y  
                                sta (F_16),y
                                sta (G_16),y
@end                           

                        dey
                        bpl @cols
                        


                dex
                bpl @rows
                rts

;;---------------------------------------------
;; draw_front_buffer
;;
;; Copies back_buffer to color_buffer
;;---------------------------------------------
draw_front_buffer 
                lda $c800
                sta $d800
                lda $c801
                sta $d801
                lda $c802
                sta $d802
                lda $c803
                sta $d803
                lda $c804
                sta $d804
                lda $c805
                sta $d805
                lda $c806
                sta $d806
                lda $c807
                sta $d807
                lda $c808
                sta $d808
                lda $c809
                sta $d809
                lda $c80a
                sta $d80a
                lda $c80b
                sta $d80b
                lda $c80c
                sta $d80c
                lda $c80d
                sta $d80d
                lda $c80e
                sta $d80e
                lda $c80f
                sta $d80f
                lda $c810
                sta $d810
                lda $c811
                sta $d811
                lda $c812
                sta $d812
                lda $c813
                sta $d813
                lda $c814
                sta $d814
                lda $c815
                sta $d815
                lda $c816
                sta $d816
                lda $c817
                sta $d817
                lda $c818
                sta $d818
                lda $c819
                sta $d819
                lda $c81a
                sta $d81a
                lda $c81b
                sta $d81b
                lda $c81c
                sta $d81c
                lda $c81d
                sta $d81d
                lda $c81e
                sta $d81e
                lda $c81f
                sta $d81f
                lda $c820
                sta $d820
                lda $c821
                sta $d821
                lda $c822
                sta $d822
                lda $c823
                sta $d823
                lda $c824
                sta $d824
                lda $c825
                sta $d825
                lda $c826
                sta $d826
                lda $c827
                sta $d827
                lda $c828
                sta $d828
                lda $c829
                sta $d829
                lda $c82a
                sta $d82a
                lda $c82b
                sta $d82b
                lda $c82c
                sta $d82c
                lda $c82d
                sta $d82d
                lda $c82e
                sta $d82e
                lda $c82f
                sta $d82f
                lda $c830
                sta $d830
                lda $c831
                sta $d831
                lda $c832
                sta $d832
                lda $c833
                sta $d833
                lda $c834
                sta $d834
                lda $c835
                sta $d835
                lda $c836
                sta $d836
                lda $c837
                sta $d837
                lda $c838
                sta $d838
                lda $c839
                sta $d839
                lda $c83a
                sta $d83a
                lda $c83b
                sta $d83b
                lda $c83c
                sta $d83c
                lda $c83d
                sta $d83d
                lda $c83e
                sta $d83e
                lda $c83f
                sta $d83f
                lda $c840
                sta $d840
                lda $c841
                sta $d841
                lda $c842
                sta $d842
                lda $c843
                sta $d843
                lda $c844
                sta $d844
                lda $c845
                sta $d845
                lda $c846
                sta $d846
                lda $c847
                sta $d847
                lda $c848
                sta $d848
                lda $c849
                sta $d849
                lda $c84a
                sta $d84a
                lda $c84b
                sta $d84b
                lda $c84c
                sta $d84c
                lda $c84d
                sta $d84d
                lda $c84e
                sta $d84e
                lda $c84f
                sta $d84f
                lda $c850
                sta $d850
                lda $c851
                sta $d851
                lda $c852
                sta $d852
                lda $c853
                sta $d853
                lda $c854
                sta $d854
                lda $c855
                sta $d855
                lda $c856
                sta $d856
                lda $c857
                sta $d857
                lda $c858
                sta $d858
                lda $c859
                sta $d859
                lda $c85a
                sta $d85a
                lda $c85b
                sta $d85b
                lda $c85c
                sta $d85c
                lda $c85d
                sta $d85d
                lda $c85e
                sta $d85e
                lda $c85f
                sta $d85f
                lda $c860
                sta $d860
                lda $c861
                sta $d861
                lda $c862
                sta $d862
                lda $c863
                sta $d863
                lda $c864
                sta $d864
                lda $c865
                sta $d865
                lda $c866
                sta $d866
                lda $c867
                sta $d867
                lda $c868
                sta $d868
                lda $c869
                sta $d869
                lda $c86a
                sta $d86a
                lda $c86b
                sta $d86b
                lda $c86c
                sta $d86c
                lda $c86d
                sta $d86d
                lda $c86e
                sta $d86e
                lda $c86f
                sta $d86f
                lda $c870
                sta $d870
                lda $c871
                sta $d871
                lda $c872
                sta $d872
                lda $c873
                sta $d873
                lda $c874
                sta $d874
                lda $c875
                sta $d875
                lda $c876
                sta $d876
                lda $c877
                sta $d877
                lda $c878
                sta $d878
                lda $c879
                sta $d879
                lda $c87a
                sta $d87a
                lda $c87b
                sta $d87b
                lda $c87c
                sta $d87c
                lda $c87d
                sta $d87d
                lda $c87e
                sta $d87e
                lda $c87f
                sta $d87f
                lda $c880
                sta $d880
                lda $c881
                sta $d881
                lda $c882
                sta $d882
                lda $c883
                sta $d883
                lda $c884
                sta $d884
                lda $c885
                sta $d885
                lda $c886
                sta $d886
                lda $c887
                sta $d887
                lda $c888
                sta $d888
                lda $c889
                sta $d889
                lda $c88a
                sta $d88a
                lda $c88b
                sta $d88b
                lda $c88c
                sta $d88c
                lda $c88d
                sta $d88d
                lda $c88e
                sta $d88e
                lda $c88f
                sta $d88f
                lda $c890
                sta $d890
                lda $c891
                sta $d891
                lda $c892
                sta $d892
                lda $c893
                sta $d893
                lda $c894
                sta $d894
                lda $c895
                sta $d895
                lda $c896
                sta $d896
                lda $c897
                sta $d897
                lda $c898
                sta $d898
                lda $c899
                sta $d899
                lda $c89a
                sta $d89a
                lda $c89b
                sta $d89b
                lda $c89c
                sta $d89c
                lda $c89d
                sta $d89d
                lda $c89e
                sta $d89e
                lda $c89f
                sta $d89f
                lda $c8a0
                sta $d8a0
                lda $c8a1
                sta $d8a1
                lda $c8a2
                sta $d8a2
                lda $c8a3
                sta $d8a3
                lda $c8a4
                sta $d8a4
                lda $c8a5
                sta $d8a5
                lda $c8a6
                sta $d8a6
                lda $c8a7
                sta $d8a7
                lda $c8a8
                sta $d8a8
                lda $c8a9
                sta $d8a9
                lda $c8aa
                sta $d8aa
                lda $c8ab
                sta $d8ab
                lda $c8ac
                sta $d8ac
                lda $c8ad
                sta $d8ad
                lda $c8ae
                sta $d8ae
                lda $c8af
                sta $d8af
                lda $c8b0
                sta $d8b0
                lda $c8b1
                sta $d8b1
                lda $c8b2
                sta $d8b2
                lda $c8b3
                sta $d8b3
                lda $c8b4
                sta $d8b4
                lda $c8b5
                sta $d8b5
                lda $c8b6
                sta $d8b6
                lda $c8b7
                sta $d8b7
                lda $c8b8
                sta $d8b8
                lda $c8b9
                sta $d8b9
                lda $c8ba
                sta $d8ba
                lda $c8bb
                sta $d8bb
                lda $c8bc
                sta $d8bc
                lda $c8bd
                sta $d8bd
                lda $c8be
                sta $d8be
                lda $c8bf
                sta $d8bf
                lda $c8c0
                sta $d8c0
                lda $c8c1
                sta $d8c1
                lda $c8c2
                sta $d8c2
                lda $c8c3
                sta $d8c3
                lda $c8c4
                sta $d8c4
                lda $c8c5
                sta $d8c5
                lda $c8c6
                sta $d8c6
                lda $c8c7
                sta $d8c7
                lda $c8c8
                sta $d8c8
                lda $c8c9
                sta $d8c9
                lda $c8ca
                sta $d8ca
                lda $c8cb
                sta $d8cb
                lda $c8cc
                sta $d8cc
                lda $c8cd
                sta $d8cd
                lda $c8ce
                sta $d8ce
                lda $c8cf
                sta $d8cf
                lda $c8d0
                sta $d8d0
                lda $c8d1
                sta $d8d1
                lda $c8d2
                sta $d8d2
                lda $c8d3
                sta $d8d3
                lda $c8d4
                sta $d8d4
                lda $c8d5
                sta $d8d5
                lda $c8d6
                sta $d8d6
                lda $c8d7
                sta $d8d7
                lda $c8d8
                sta $d8d8
                lda $c8d9
                sta $d8d9
                lda $c8da
                sta $d8da
                lda $c8db
                sta $d8db
                lda $c8dc
                sta $d8dc
                lda $c8dd
                sta $d8dd
                lda $c8de
                sta $d8de
                lda $c8df
                sta $d8df
                lda $c8e0
                sta $d8e0
                lda $c8e1
                sta $d8e1
                lda $c8e2
                sta $d8e2
                lda $c8e3
                sta $d8e3
                lda $c8e4
                sta $d8e4
                lda $c8e5
                sta $d8e5
                lda $c8e6
                sta $d8e6
                lda $c8e7
                sta $d8e7
                lda $c8e8
                sta $d8e8
                lda $c8e9
                sta $d8e9
                lda $c8ea
                sta $d8ea
                lda $c8eb
                sta $d8eb
                lda $c8ec
                sta $d8ec
                lda $c8ed
                sta $d8ed
                lda $c8ee
                sta $d8ee
                lda $c8ef
                sta $d8ef
                lda $c8f0
                sta $d8f0
                lda $c8f1
                sta $d8f1
                lda $c8f2
                sta $d8f2
                lda $c8f3
                sta $d8f3
                lda $c8f4
                sta $d8f4
                lda $c8f5
                sta $d8f5
                lda $c8f6
                sta $d8f6
                lda $c8f7
                sta $d8f7
                lda $c8f8
                sta $d8f8
                lda $c8f9
                sta $d8f9
                lda $c8fa
                sta $d8fa
                lda $c8fb
                sta $d8fb
                lda $c8fc
                sta $d8fc
                lda $c8fd
                sta $d8fd
                lda $c8fe
                sta $d8fe
                lda $c8ff
                sta $d8ff
                lda $c900
                sta $d900
                lda $c901
                sta $d901
                lda $c902
                sta $d902
                lda $c903
                sta $d903
                lda $c904
                sta $d904
                lda $c905
                sta $d905
                lda $c906
                sta $d906
                lda $c907
                sta $d907
                lda $c908
                sta $d908
                lda $c909
                sta $d909
                lda $c90a
                sta $d90a
                lda $c90b
                sta $d90b
                lda $c90c
                sta $d90c
                lda $c90d
                sta $d90d
                lda $c90e
                sta $d90e
                lda $c90f
                sta $d90f
                lda $c910
                sta $d910
                lda $c911
                sta $d911
                lda $c912
                sta $d912
                lda $c913
                sta $d913
                lda $c914
                sta $d914
                lda $c915
                sta $d915
                lda $c916
                sta $d916
                lda $c917
                sta $d917
                lda $c918
                sta $d918
                lda $c919
                sta $d919
                lda $c91a
                sta $d91a
                lda $c91b
                sta $d91b
                lda $c91c
                sta $d91c
                lda $c91d
                sta $d91d
                lda $c91e
                sta $d91e
                lda $c91f
                sta $d91f
                lda $c920
                sta $d920
                lda $c921
                sta $d921
                lda $c922
                sta $d922
                lda $c923
                sta $d923
                lda $c924
                sta $d924
                lda $c925
                sta $d925
                lda $c926
                sta $d926
                lda $c927
                sta $d927
                lda $c928
                sta $d928
                lda $c929
                sta $d929
                lda $c92a
                sta $d92a
                lda $c92b
                sta $d92b
                lda $c92c
                sta $d92c
                lda $c92d
                sta $d92d
                lda $c92e
                sta $d92e
                lda $c92f
                sta $d92f
                lda $c930
                sta $d930
                lda $c931
                sta $d931
                lda $c932
                sta $d932
                lda $c933
                sta $d933
                lda $c934
                sta $d934
                lda $c935
                sta $d935
                lda $c936
                sta $d936
                lda $c937
                sta $d937
                lda $c938
                sta $d938
                lda $c939
                sta $d939
                lda $c93a
                sta $d93a
                lda $c93b
                sta $d93b
                lda $c93c
                sta $d93c
                lda $c93d
                sta $d93d
                lda $c93e
                sta $d93e
                lda $c93f
                sta $d93f
                lda $c940
                sta $d940
                lda $c941
                sta $d941
                lda $c942
                sta $d942
                lda $c943
                sta $d943
                lda $c944
                sta $d944
                lda $c945
                sta $d945
                lda $c946
                sta $d946
                lda $c947
                sta $d947
                lda $c948
                sta $d948
                lda $c949
                sta $d949
                lda $c94a
                sta $d94a
                lda $c94b
                sta $d94b
                lda $c94c
                sta $d94c
                lda $c94d
                sta $d94d
                lda $c94e
                sta $d94e
                lda $c94f
                sta $d94f
                lda $c950
                sta $d950
                lda $c951
                sta $d951
                lda $c952
                sta $d952
                lda $c953
                sta $d953
                lda $c954
                sta $d954
                lda $c955
                sta $d955
                lda $c956
                sta $d956
                lda $c957
                sta $d957
                lda $c958
                sta $d958
                lda $c959
                sta $d959
                lda $c95a
                sta $d95a
                lda $c95b
                sta $d95b
                lda $c95c
                sta $d95c
                lda $c95d
                sta $d95d
                lda $c95e
                sta $d95e
                lda $c95f
                sta $d95f
                lda $c960
                sta $d960
                lda $c961
                sta $d961
                lda $c962
                sta $d962
                lda $c963
                sta $d963
                lda $c964
                sta $d964
                lda $c965
                sta $d965
                lda $c966
                sta $d966
                lda $c967
                sta $d967
                lda $c968
                sta $d968
                lda $c969
                sta $d969
                lda $c96a
                sta $d96a
                lda $c96b
                sta $d96b
                lda $c96c
                sta $d96c
                lda $c96d
                sta $d96d
                lda $c96e
                sta $d96e
                lda $c96f
                sta $d96f
                lda $c970
                sta $d970
                lda $c971
                sta $d971
                lda $c972
                sta $d972
                lda $c973
                sta $d973
                lda $c974
                sta $d974
                lda $c975
                sta $d975
                lda $c976
                sta $d976
                lda $c977
                sta $d977
                lda $c978
                sta $d978
                lda $c979
                sta $d979
                lda $c97a
                sta $d97a
                lda $c97b
                sta $d97b
                lda $c97c
                sta $d97c
                lda $c97d
                sta $d97d
                lda $c97e
                sta $d97e
                lda $c97f
                sta $d97f
                lda $c980
                sta $d980
                lda $c981
                sta $d981
                lda $c982
                sta $d982
                lda $c983
                sta $d983
                lda $c984
                sta $d984
                lda $c985
                sta $d985
                lda $c986
                sta $d986
                lda $c987
                sta $d987
                lda $c988
                sta $d988
                lda $c989
                sta $d989
                lda $c98a
                sta $d98a
                lda $c98b
                sta $d98b
                lda $c98c
                sta $d98c
                lda $c98d
                sta $d98d
                lda $c98e
                sta $d98e
                lda $c98f
                sta $d98f
                lda $c990
                sta $d990
                lda $c991
                sta $d991
                lda $c992
                sta $d992
                lda $c993
                sta $d993
                lda $c994
                sta $d994
                lda $c995
                sta $d995
                lda $c996
                sta $d996
                lda $c997
                sta $d997
                lda $c998
                sta $d998
                lda $c999
                sta $d999
                lda $c99a
                sta $d99a
                lda $c99b
                sta $d99b
                lda $c99c
                sta $d99c
                lda $c99d
                sta $d99d
                lda $c99e
                sta $d99e
                lda $c99f
                sta $d99f
                lda $c9a0
                sta $d9a0
                lda $c9a1
                sta $d9a1
                lda $c9a2
                sta $d9a2
                lda $c9a3
                sta $d9a3
                lda $c9a4
                sta $d9a4
                lda $c9a5
                sta $d9a5
                lda $c9a6
                sta $d9a6
                lda $c9a7
                sta $d9a7
                lda $c9a8
                sta $d9a8
                lda $c9a9
                sta $d9a9
                lda $c9aa
                sta $d9aa
                lda $c9ab
                sta $d9ab
                lda $c9ac
                sta $d9ac
                lda $c9ad
                sta $d9ad
                lda $c9ae
                sta $d9ae
                lda $c9af
                sta $d9af
                lda $c9b0
                sta $d9b0
                lda $c9b1
                sta $d9b1
                lda $c9b2
                sta $d9b2
                lda $c9b3
                sta $d9b3
                lda $c9b4
                sta $d9b4
                lda $c9b5
                sta $d9b5
                lda $c9b6
                sta $d9b6
                lda $c9b7
                sta $d9b7
                lda $c9b8
                sta $d9b8
                lda $c9b9
                sta $d9b9
                lda $c9ba
                sta $d9ba
                lda $c9bb
                sta $d9bb
                lda $c9bc
                sta $d9bc
                lda $c9bd
                sta $d9bd
                lda $c9be
                sta $d9be
                lda $c9bf
                sta $d9bf
                lda $c9c0
                sta $d9c0
                lda $c9c1
                sta $d9c1
                lda $c9c2
                sta $d9c2
                lda $c9c3
                sta $d9c3
                lda $c9c4
                sta $d9c4
                lda $c9c5
                sta $d9c5
                lda $c9c6
                sta $d9c6
                lda $c9c7
                sta $d9c7
                lda $c9c8
                sta $d9c8
                lda $c9c9
                sta $d9c9
                lda $c9ca
                sta $d9ca
                lda $c9cb
                sta $d9cb
                lda $c9cc
                sta $d9cc
                lda $c9cd
                sta $d9cd
                lda $c9ce
                sta $d9ce
                lda $c9cf
                sta $d9cf
                lda $c9d0
                sta $d9d0
                lda $c9d1
                sta $d9d1
                lda $c9d2
                sta $d9d2
                lda $c9d3
                sta $d9d3
                lda $c9d4
                sta $d9d4
                lda $c9d5
                sta $d9d5
                lda $c9d6
                sta $d9d6
                lda $c9d7
                sta $d9d7
                lda $c9d8
                sta $d9d8
                lda $c9d9
                sta $d9d9
                lda $c9da
                sta $d9da
                lda $c9db
                sta $d9db
                lda $c9dc
                sta $d9dc
                lda $c9dd
                sta $d9dd
                lda $c9de
                sta $d9de
                lda $c9df
                sta $d9df
                lda $c9e0
                sta $d9e0
                lda $c9e1
                sta $d9e1
                lda $c9e2
                sta $d9e2
                lda $c9e3
                sta $d9e3
                lda $c9e4
                sta $d9e4
                lda $c9e5
                sta $d9e5
                lda $c9e6
                sta $d9e6
                lda $c9e7
                sta $d9e7
                lda $c9e8
                sta $d9e8
                lda $c9e9
                sta $d9e9
                lda $c9ea
                sta $d9ea
                lda $c9eb
                sta $d9eb
                lda $c9ec
                sta $d9ec
                lda $c9ed
                sta $d9ed
                lda $c9ee
                sta $d9ee
                lda $c9ef
                sta $d9ef
                lda $c9f0
                sta $d9f0
                lda $c9f1
                sta $d9f1
                lda $c9f2
                sta $d9f2
                lda $c9f3
                sta $d9f3
                lda $c9f4
                sta $d9f4
                lda $c9f5
                sta $d9f5
                lda $c9f6
                sta $d9f6
                lda $c9f7
                sta $d9f7
                lda $c9f8
                sta $d9f8
                lda $c9f9
                sta $d9f9
                lda $c9fa
                sta $d9fa
                lda $c9fb
                sta $d9fb
                lda $c9fc
                sta $d9fc
                lda $c9fd
                sta $d9fd
                lda $c9fe
                sta $d9fe
                lda $c9ff
                sta $d9ff
                lda $ca00
                sta $da00
                lda $ca01
                sta $da01
                lda $ca02
                sta $da02
                lda $ca03
                sta $da03
                lda $ca04
                sta $da04
                lda $ca05
                sta $da05
                lda $ca06
                sta $da06
                lda $ca07
                sta $da07
                lda $ca08
                sta $da08
                lda $ca09
                sta $da09
                lda $ca0a
                sta $da0a
                lda $ca0b
                sta $da0b
                lda $ca0c
                sta $da0c
                lda $ca0d
                sta $da0d
                lda $ca0e
                sta $da0e
                lda $ca0f
                sta $da0f
                lda $ca10
                sta $da10
                lda $ca11
                sta $da11
                lda $ca12
                sta $da12
                lda $ca13
                sta $da13
                lda $ca14
                sta $da14
                lda $ca15
                sta $da15
                lda $ca16
                sta $da16
                lda $ca17
                sta $da17
                lda $ca18
                sta $da18
                lda $ca19
                sta $da19
                lda $ca1a
                sta $da1a
                lda $ca1b
                sta $da1b
                lda $ca1c
                sta $da1c
                lda $ca1d
                sta $da1d
                lda $ca1e
                sta $da1e
                lda $ca1f
                sta $da1f
                lda $ca20
                sta $da20
                lda $ca21
                sta $da21
                lda $ca22
                sta $da22
                lda $ca23
                sta $da23
                lda $ca24
                sta $da24
                lda $ca25
                sta $da25
                lda $ca26
                sta $da26
                lda $ca27
                sta $da27
                lda $ca28
                sta $da28
                lda $ca29
                sta $da29
                lda $ca2a
                sta $da2a
                lda $ca2b
                sta $da2b
                lda $ca2c
                sta $da2c
                lda $ca2d
                sta $da2d
                lda $ca2e
                sta $da2e
                lda $ca2f
                sta $da2f
                lda $ca30
                sta $da30
                lda $ca31
                sta $da31
                lda $ca32
                sta $da32
                lda $ca33
                sta $da33
                lda $ca34
                sta $da34
                lda $ca35
                sta $da35
                lda $ca36
                sta $da36
                lda $ca37
                sta $da37
                lda $ca38
                sta $da38
                lda $ca39
                sta $da39
                lda $ca3a
                sta $da3a
                lda $ca3b
                sta $da3b
                lda $ca3c
                sta $da3c
                lda $ca3d
                sta $da3d
                lda $ca3e
                sta $da3e
                lda $ca3f
                sta $da3f
                lda $ca40
                sta $da40
                lda $ca41
                sta $da41
                lda $ca42
                sta $da42
                lda $ca43
                sta $da43
                lda $ca44
                sta $da44
                lda $ca45
                sta $da45
                lda $ca46
                sta $da46
                lda $ca47
                sta $da47
                lda $ca48
                sta $da48
                lda $ca49
                sta $da49
                lda $ca4a
                sta $da4a
                lda $ca4b
                sta $da4b
                lda $ca4c
                sta $da4c
                lda $ca4d
                sta $da4d
                lda $ca4e
                sta $da4e
                lda $ca4f
                sta $da4f
                lda $ca50
                sta $da50
                lda $ca51
                sta $da51
                lda $ca52
                sta $da52
                lda $ca53
                sta $da53
                lda $ca54
                sta $da54
                lda $ca55
                sta $da55
                lda $ca56
                sta $da56
                lda $ca57
                sta $da57
                lda $ca58
                sta $da58
                lda $ca59
                sta $da59
                lda $ca5a
                sta $da5a
                lda $ca5b
                sta $da5b
                lda $ca5c
                sta $da5c
                lda $ca5d
                sta $da5d
                lda $ca5e
                sta $da5e
                lda $ca5f
                sta $da5f
                lda $ca60
                sta $da60
                lda $ca61
                sta $da61
                lda $ca62
                sta $da62
                lda $ca63
                sta $da63
                lda $ca64
                sta $da64
                lda $ca65
                sta $da65
                lda $ca66
                sta $da66
                lda $ca67
                sta $da67
                lda $ca68
                sta $da68
                lda $ca69
                sta $da69
                lda $ca6a
                sta $da6a
                lda $ca6b
                sta $da6b
                lda $ca6c
                sta $da6c
                lda $ca6d
                sta $da6d
                lda $ca6e
                sta $da6e
                lda $ca6f
                sta $da6f
                lda $ca70
                sta $da70
                lda $ca71
                sta $da71
                lda $ca72
                sta $da72
                lda $ca73
                sta $da73
                lda $ca74
                sta $da74
                lda $ca75
                sta $da75
                lda $ca76
                sta $da76
                lda $ca77
                sta $da77
                lda $ca78
                sta $da78
                lda $ca79
                sta $da79
                lda $ca7a
                sta $da7a
                lda $ca7b
                sta $da7b
                lda $ca7c
                sta $da7c
                lda $ca7d
                sta $da7d
                lda $ca7e
                sta $da7e
                lda $ca7f
                sta $da7f
                lda $ca80
                sta $da80
                lda $ca81
                sta $da81
                lda $ca82
                sta $da82
                lda $ca83
                sta $da83
                lda $ca84
                sta $da84
                lda $ca85
                sta $da85
                lda $ca86
                sta $da86
                lda $ca87
                sta $da87
                lda $ca88
                sta $da88
                lda $ca89
                sta $da89
                lda $ca8a
                sta $da8a
                lda $ca8b
                sta $da8b
                lda $ca8c
                sta $da8c
                lda $ca8d
                sta $da8d
                lda $ca8e
                sta $da8e
                lda $ca8f
                sta $da8f
                lda $ca90
                sta $da90
                lda $ca91
                sta $da91
                lda $ca92
                sta $da92
                lda $ca93
                sta $da93
                lda $ca94
                sta $da94
                lda $ca95
                sta $da95
                lda $ca96
                sta $da96
                lda $ca97
                sta $da97
                lda $ca98
                sta $da98
                lda $ca99
                sta $da99
                lda $ca9a
                sta $da9a
                lda $ca9b
                sta $da9b
                lda $ca9c
                sta $da9c
                lda $ca9d
                sta $da9d
                lda $ca9e
                sta $da9e
                lda $ca9f
                sta $da9f
                lda $caa0
                sta $daa0
                lda $caa1
                sta $daa1
                lda $caa2
                sta $daa2
                lda $caa3
                sta $daa3
                lda $caa4
                sta $daa4
                lda $caa5
                sta $daa5
                lda $caa6
                sta $daa6
                lda $caa7
                sta $daa7
                lda $caa8
                sta $daa8
                lda $caa9
                sta $daa9
                lda $caaa
                sta $daaa
                lda $caab
                sta $daab
                lda $caac
                sta $daac
                lda $caad
                sta $daad
                lda $caae
                sta $daae
                lda $caaf
                sta $daaf
                lda $cab0
                sta $dab0
                lda $cab1
                sta $dab1
                lda $cab2
                sta $dab2
                lda $cab3
                sta $dab3
                lda $cab4
                sta $dab4
                lda $cab5
                sta $dab5
                lda $cab6
                sta $dab6
                lda $cab7
                sta $dab7
                lda $cab8
                sta $dab8
                lda $cab9
                sta $dab9
                lda $caba
                sta $daba
                lda $cabb
                sta $dabb
                lda $cabc
                sta $dabc
                lda $cabd
                sta $dabd
                lda $cabe
                sta $dabe
                lda $cabf
                sta $dabf
                lda $cac0
                sta $dac0
                lda $cac1
                sta $dac1
                lda $cac2
                sta $dac2
                lda $cac3
                sta $dac3
                lda $cac4
                sta $dac4
                lda $cac5
                sta $dac5
                lda $cac6
                sta $dac6
                lda $cac7
                sta $dac7
                lda $cac8
                sta $dac8
                lda $cac9
                sta $dac9
                lda $caca
                sta $daca
                lda $cacb
                sta $dacb
                lda $cacc
                sta $dacc
                lda $cacd
                sta $dacd
                lda $cace
                sta $dace
                lda $cacf
                sta $dacf
                lda $cad0
                sta $dad0
                lda $cad1
                sta $dad1
                lda $cad2
                sta $dad2
                lda $cad3
                sta $dad3
                lda $cad4
                sta $dad4
                lda $cad5
                sta $dad5
                lda $cad6
                sta $dad6
                lda $cad7
                sta $dad7
                lda $cad8
                sta $dad8
                lda $cad9
                sta $dad9
                lda $cada
                sta $dada
                lda $cadb
                sta $dadb
                lda $cadc
                sta $dadc
                lda $cadd
                sta $dadd
                lda $cade
                sta $dade
                lda $cadf
                sta $dadf
                lda $cae0
                sta $dae0
                lda $cae1
                sta $dae1
                lda $cae2
                sta $dae2
                lda $cae3
                sta $dae3
                lda $cae4
                sta $dae4
                lda $cae5
                sta $dae5
                lda $cae6
                sta $dae6
                lda $cae7
                sta $dae7
                lda $cae8
                sta $dae8
                lda $cae9
                sta $dae9
                lda $caea
                sta $daea
                lda $caeb
                sta $daeb
                lda $caec
                sta $daec
                lda $caed
                sta $daed
                lda $caee
                sta $daee
                lda $caef
                sta $daef
                lda $caf0
                sta $daf0
                lda $caf1
                sta $daf1
                lda $caf2
                sta $daf2
                lda $caf3
                sta $daf3
                lda $caf4
                sta $daf4
                lda $caf5
                sta $daf5
                lda $caf6
                sta $daf6
                lda $caf7
                sta $daf7
                lda $caf8
                sta $daf8
                lda $caf9
                sta $daf9
                lda $cafa
                sta $dafa
                lda $cafb
                sta $dafb
                lda $cafc
                sta $dafc
                lda $cafd
                sta $dafd
                lda $cafe
                sta $dafe
                lda $caff
                sta $daff
                lda $cb00
                sta $db00
                lda $cb01
                sta $db01
                lda $cb02
                sta $db02
                lda $cb03
                sta $db03
                lda $cb04
                sta $db04
                lda $cb05
                sta $db05
                lda $cb06
                sta $db06
                lda $cb07
                sta $db07
                lda $cb08
                sta $db08
                lda $cb09
                sta $db09
                lda $cb0a
                sta $db0a
                lda $cb0b
                sta $db0b
                lda $cb0c
                sta $db0c
                lda $cb0d
                sta $db0d
                lda $cb0e
                sta $db0e
                lda $cb0f
                sta $db0f
                lda $cb10
                sta $db10
                lda $cb11
                sta $db11
                lda $cb12
                sta $db12
                lda $cb13
                sta $db13
                lda $cb14
                sta $db14
                lda $cb15
                sta $db15
                lda $cb16
                sta $db16
                lda $cb17
                sta $db17
                lda $cb18
                sta $db18
                lda $cb19
                sta $db19
                lda $cb1a
                sta $db1a
                lda $cb1b
                sta $db1b
                lda $cb1c
                sta $db1c
                lda $cb1d
                sta $db1d
                lda $cb1e
                sta $db1e
                lda $cb1f
                sta $db1f
                lda $cb20
                sta $db20
                lda $cb21
                sta $db21
                lda $cb22
                sta $db22
                lda $cb23
                sta $db23
                lda $cb24
                sta $db24
                lda $cb25
                sta $db25
                lda $cb26
                sta $db26
                lda $cb27
                sta $db27
                lda $cb28
                sta $db28
                lda $cb29
                sta $db29
                lda $cb2a
                sta $db2a
                lda $cb2b
                sta $db2b
                lda $cb2c
                sta $db2c
                lda $cb2d
                sta $db2d
                lda $cb2e
                sta $db2e
                lda $cb2f
                sta $db2f
                lda $cb30
                sta $db30
                lda $cb31
                sta $db31
                lda $cb32
                sta $db32
                lda $cb33
                sta $db33
                lda $cb34
                sta $db34
                lda $cb35
                sta $db35
                lda $cb36
                sta $db36
                lda $cb37
                sta $db37
                lda $cb38
                sta $db38
                lda $cb39
                sta $db39
                lda $cb3a
                sta $db3a
                lda $cb3b
                sta $db3b
                lda $cb3c
                sta $db3c
                lda $cb3d
                sta $db3d
                lda $cb3e
                sta $db3e
                lda $cb3f
                sta $db3f
                lda $cb40
                sta $db40
                lda $cb41
                sta $db41
                lda $cb42
                sta $db42
                lda $cb43
                sta $db43
                lda $cb44
                sta $db44
                lda $cb45
                sta $db45
                lda $cb46
                sta $db46
                lda $cb47
                sta $db47
                lda $cb48
                sta $db48
                lda $cb49
                sta $db49
                lda $cb4a
                sta $db4a
                lda $cb4b
                sta $db4b
                lda $cb4c
                sta $db4c
                lda $cb4d
                sta $db4d
                lda $cb4e
                sta $db4e
                lda $cb4f
                sta $db4f
                lda $cb50
                sta $db50
                lda $cb51
                sta $db51
                lda $cb52
                sta $db52
                lda $cb53
                sta $db53
                lda $cb54
                sta $db54
                lda $cb55
                sta $db55
                lda $cb56
                sta $db56
                lda $cb57
                sta $db57
                lda $cb58
                sta $db58
                lda $cb59
                sta $db59
                lda $cb5a
                sta $db5a
                lda $cb5b
                sta $db5b
                lda $cb5c
                sta $db5c
                lda $cb5d
                sta $db5d
                lda $cb5e
                sta $db5e
                lda $cb5f
                sta $db5f
                lda $cb60
                sta $db60
                lda $cb61
                sta $db61
                lda $cb62
                sta $db62
                lda $cb63
                sta $db63
                lda $cb64
                sta $db64
                lda $cb65
                sta $db65
                lda $cb66
                sta $db66
                lda $cb67
                sta $db67
                lda $cb68
                sta $db68
                lda $cb69
                sta $db69
                lda $cb6a
                sta $db6a
                lda $cb6b
                sta $db6b
                lda $cb6c
                sta $db6c
                lda $cb6d
                sta $db6d
                lda $cb6e
                sta $db6e
                lda $cb6f
                sta $db6f
                lda $cb70
                sta $db70
                lda $cb71
                sta $db71
                lda $cb72
                sta $db72
                lda $cb73
                sta $db73
                lda $cb74
                sta $db74
                lda $cb75
                sta $db75
                lda $cb76
                sta $db76
                lda $cb77
                sta $db77
                lda $cb78
                sta $db78
                lda $cb79
                sta $db79
                lda $cb7a
                sta $db7a
                lda $cb7b
                sta $db7b
                lda $cb7c
                sta $db7c
                lda $cb7d
                sta $db7d
                lda $cb7e
                sta $db7e
                lda $cb7f
                sta $db7f
                lda $cb80
                sta $db80
                lda $cb81
                sta $db81
                lda $cb82
                sta $db82
                lda $cb83
                sta $db83
                lda $cb84
                sta $db84
                lda $cb85
                sta $db85
                lda $cb86
                sta $db86
                lda $cb87
                sta $db87
                lda $cb88
                sta $db88
                lda $cb89
                sta $db89
                lda $cb8a
                sta $db8a
                lda $cb8b
                sta $db8b
                lda $cb8c
                sta $db8c
                lda $cb8d
                sta $db8d
                lda $cb8e
                sta $db8e
                lda $cb8f
                sta $db8f
                lda $cb90
                sta $db90
                lda $cb91
                sta $db91
                lda $cb92
                sta $db92
                lda $cb93
                sta $db93
                lda $cb94
                sta $db94
                lda $cb95
                sta $db95
                lda $cb96
                sta $db96
                lda $cb97
                sta $db97
                lda $cb98
                sta $db98
                lda $cb99
                sta $db99
                lda $cb9a
                sta $db9a
                lda $cb9b
                sta $db9b
                lda $cb9c
                sta $db9c
                lda $cb9d
                sta $db9d
                lda $cb9e
                sta $db9e
                lda $cb9f
                sta $db9f
                lda $cba0
                sta $dba0
                lda $cba1
                sta $dba1
                lda $cba2
                sta $dba2
                lda $cba3
                sta $dba3
                lda $cba4
                sta $dba4
                lda $cba5
                sta $dba5
                lda $cba6
                sta $dba6
                lda $cba7
                sta $dba7
                lda $cba8
                sta $dba8
                lda $cba9
                sta $dba9
                lda $cbaa
                sta $dbaa
                lda $cbab
                sta $dbab
                lda $cbac
                sta $dbac
                lda $cbad
                sta $dbad
                lda $cbae
                sta $dbae
                lda $cbaf
                sta $dbaf
                lda $cbb0
                sta $dbb0
                lda $cbb1
                sta $dbb1
                lda $cbb2
                sta $dbb2
                lda $cbb3
                sta $dbb3
                lda $cbb4
                sta $dbb4
                lda $cbb5
                sta $dbb5
                lda $cbb6
                sta $dbb6
                lda $cbb7
                sta $dbb7
                lda $cbb8
                sta $dbb8
                lda $cbb9
                sta $dbb9
                lda $cbba
                sta $dbba
                lda $cbbb
                sta $dbbb
                lda $cbbc
                sta $dbbc
                lda $cbbd
                sta $dbbd
                lda $cbbe
                sta $dbbe
                lda $cbbf
                sta $dbbf
                lda $cbc0
                sta $dbc0
                lda $cbc1
                sta $dbc1
                lda $cbc2
                sta $dbc2
                lda $cbc3
                sta $dbc3
                lda $cbc4
                sta $dbc4
                lda $cbc5
                sta $dbc5
                lda $cbc6
                sta $dbc6
                lda $cbc7
                sta $dbc7
                lda $cbc8
                sta $dbc8
                lda $cbc9
                sta $dbc9
                lda $cbca
                sta $dbca
                lda $cbcb
                sta $dbcb
                lda $cbcc
                sta $dbcc
                lda $cbcd
                sta $dbcd
                lda $cbce
                sta $dbce
                lda $cbcf
                sta $dbcf
                lda $cbd0
                sta $dbd0
                lda $cbd1
                sta $dbd1
                lda $cbd2
                sta $dbd2
                lda $cbd3
                sta $dbd3
                lda $cbd4
                sta $dbd4
                lda $cbd5
                sta $dbd5
                lda $cbd6
                sta $dbd6
                lda $cbd7
                sta $dbd7
                lda $cbd8
                sta $dbd8
                lda $cbd9
                sta $dbd9
                lda $cbda
                sta $dbda
                lda $cbdb
                sta $dbdb
                lda $cbdc
                sta $dbdc
                lda $cbdd
                sta $dbdd
                lda $cbde
                sta $dbde
                lda $cbdf
                sta $dbdf
                lda $cbe0
                sta $dbe0
                lda $cbe1
                sta $dbe1
                lda $cbe2
                sta $dbe2
                lda $cbe3
                sta $dbe3
                lda $cbe4
                sta $dbe4
                lda $cbe5
                sta $dbe5
                lda $cbe6
                sta $dbe6
                lda $cbe7
                sta $dbe7
                rts